# Homework 10 Numpy

## Task 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [19]:
import numpy as np

N = 10

x = np.arange(N-1,0,-1)

print(x, type(x))
x

[9 8 7 6 5 4 3 2 1] <class 'numpy.ndarray'>


array([9, 8, 7, 6, 5, 4, 3, 2, 1])

## Task 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [28]:
import numpy as np

N = 10

x = np.diag(np.arange(N-1,0,-1))

print(x, np.trace(x))

[[9 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 4 0 0 0]
 [0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 1]] 45


## Task 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [31]:
import numpy as np

l = np.array([ [4, 2, 1], 
               [1, 3, 0],
               [0, 5, 4] ])

r = np.array( [4, 12, -3] )

np.linalg.solve(l,r)

array([ 0.46666667,  3.84444444, -5.55555556])

## Task 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.
На сайт заходит очередной посетитель, о покупках которого известно следующее.
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats.

In [68]:
import numpy as np


class NumpyTsk:
    def __init__(self, gen_stat, new_usr):
        self.pool = gen_stat
        self.usr  = new_usr
        
    @staticmethod
    def cosim(unit_1, unit_2):
        """ Returns cosine similarity of 2 given vectors"""
        return np.dot(unit_1, unit_2)/(np.linalg.norm(unit_1) * np.linalg.norm(unit_2))
        
    def find_similarity(self):
        """ 
        Returns a dict consists of cosine similarity between each vector from an array 'gen_stat'
        and a single vector 'new_usr' (both given to the class instance); 
        dictionary keys - indexes of the appropriate array 'gen_stat' elements
        """
        similarity = {}
        
        for i, unit in enumerate(self.pool):
            similarity.setdefault(i)
            similarity[i] = self.cosim(self.usr, unit)
        
        return similarity
    
        
#########

        
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

exmpl = NumpyTsk(users_stats, next_user_stats)


similarity = exmpl.find_similarity()
similarity

#max_sim_idx = max(similarity, key=similarity.get)
#print('Max similarity', similarity[max_sim_idx], 'to the new user shows a user with ID', max_sim_idx )

{0: 0.19999999999999996,
 1: 0.8451542547285165,
 2: 0.3999999999999999,
 3: 0.7905694150420948,
 4: 0.3999999999999999,
 5: 0.0,
 6: 0.0,
 7: 0.9486832980505138,
 8: 0.0,
 9: 0.0}